### ISSUE TITLE
Feature Proposal support OpenTelemetry on syslog drains

### ISSUE THREAD

**Issue by KarstenSchnitter** [cloudfoundry/loggregator-release#438]
As a user I would like to receive the logs of my application on OpenTelemetry format so I can create a syslog drain to a standard tool such as the OpenTelemetry Collector. 

Using the [OpenTelemetry log format](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md) will enable log ingestion into a variety of services, e.g. Elasticsearch supports OpenTelemetry out of the box. The metadata currently provided as syslog structured data should be added as resource attributes. See the [protobuf definitions](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto) for details on the format. 

During the registration of the syslog drain url custom certificates should be supported, so that mTLS can be achieved.

**Comment by ctlong** [comment]
@KarstenSchnitter it sounds like you're asking for application logs to be formatted as OpenTelemetry logs and sent via syslog? Is that right?

**Comment by Benjamintf1** [comment]
@ctlong I'd assume it means opentelemetry INSTEAD OF syslog

**Comment by ctlong** [comment]
@Benjamintf1 in terms of implementation yes, I agree. I was trying - and apparently failing - to articulate that the registered egress of the OpenTelemetry collector would be syslog.

In any case, reimplementing loggregator with OpenTelemetry seems like more effort than it's worth since we're in the process of moving to Shared Nothing. Although it does sound like we need to provide an ingress option for syslog into Elasticsearch. I would probably prefer to find another solution than reimplementing the syslog agent as an OpenTelemetry agent.

**Comment by ctlong** [comment]
Closing due to lack of response. Please feel free to re-open if there's more to do.
